# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    uploads_directory: '%kernel.project_dir%/public/uploads'  # Définition du paramètre uploads_directory
    stripe_public_key: '%env(STRIPE_PUBLIC_KEY)%'
    stripe_secret_key: '%env(STRIPE_SECRET_KEY)%'
    stripe_webhook: '%env(STRIPE_WEBHOOK)%'


services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
     
    # Ajoute explicitement CartService si nécessaire
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\checkoutService:
        arguments: ['%stripe_secret_key%', '%stripe_webhook%']
         
    App\Service\ProductService:
        arguments:
            $uploadsDirectory: '%uploads_directory%'  # Injecte le paramètre uploads_directory

    # Définition explicite de ton MailerService avec ses dépendances
    App\Service\MailerService:
        arguments:
            $mailer: '@mailer.mailer'     # Injecte le service Mailer
            $logger: '@logger'             # Injecte le service Logger

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
